version: 2.1

jobs:
  build:
    docker: circleci/node:13.8.0
  steps:
    - checkout:
    - run:  npm run lint

  test:
    docker: circleci/node:13.8.0
  steps:
    - checkout:
    - run:  npm run test

  analyze:
    docker: circleci/node:13.8.0
  steps:
    - checkout:
    - run:  npm audit

workflow:
  jobs:
    - build
    - test:
      requires:
        - build
    - analyze:
      requires:
        - test


